[Mobi-21-landing-page-top-desktop-publishing] Feat: landing page top 부분 퍼블리싱 작업을 완료합니다.
team-mobi/mobi-client pull request #6
Opened 2024-06-17 15:31 UTC by JeongwooHam

## 🌱 작업 개요

- 랜딩 페이지 상단 부분 퍼블리싱을 완료하였습니다.
- 배너 하단 영역 좌측은 `WheelEvent`와  `IntersectionObserver`를 활용하여 마우스 이벤트를 감지해 내용이 변환됩니다.
- 배너 하단 영역 우측의 경우 자동 이미지 슬라이드가 적용됩니다.
- 공용 Nav 컴포넌트가 구현되었습니다. Nav에 대한 별도의 디자인 요청 사항이 존재하지 않아 우선 일반적인 페이지들처럼  `backdrop-blur` 처리 후 스크롤을 내려도 따라다닐 수 있게 구현하였습니다.

> 해당 컴포넌트의 경우 훅함수와 함께 사용되어야 해서 우선 `feature` 폴더에 구현해두었습니다. 공용 컴포넌트이다보니 `packages/ui`에 들어가야 할지 고민이 되는데 의견 주시면 감사하겠습니다.

> 상태 관리의 경우 퍼블리싱 단계에서 상태 관리 라이브러리 의존성까지 추가하는 것은 적절하지 않을 것 같아 우선 모두 `useState`를 사용하여 구현하였습니다.

## 🧐 중요한 변경 사항

![제목 없는 동영상 - Clipchamp로 제작](https://github.com/team-mobi/mobi-client/assets/123251211/43ed9b4e-d6f2-48d9-9f00-4ed2fc66cb88)

> `Button`

- border만 존재하는 `ghost` 속성과 버튼 스타일이 존재하지 않는 `empty` 속성이 추가되었습니다. 
```ts
ghost: ['bg-transparent', 'border', 'border-2', 'border-green', 'text-green'],
empty: ['bg-transparent', 'p-0']
```
- `border-radius` 속성을 위한 `rounded` 속성이 추가되었습니다.
```ts
rounded: { full: 'rounded-full', square: 'rounded-none' }
```
- `large` 사이즈가 추가되었습니다.

> `packages/ui/src/imageSlider.tsx`

- 흘러가는 형태의 이미지 슬라이드가 사용되는 부분이 많은 것 같아 `ImageSlider`라는 공용 컴포넌트를 구현해볼 예정입니다. 현재는 슬라이드의 방향과 간격 설정이 가능합니다.

> `global.css`

- 커스텀 애니메이션 구현 사항이 추가되었습니다. 아래에도 적은 것처럼, tailwindconfing를 사용한 keyframe의 확장이 적용되지 않아 부득이하게 global.css에서 keyframes를 정의하고 class명을 작성하였습니다.

```css
@keyframes verticalSlider {
  0% {
    transform: translateY(0);
  }
  100% {
    transform: translateY(100px);
  }
}

.vertical-slider {
  animation: verticalSlider 3s linear infinite;
}

@keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.fade-in {
  animation: fadein 2s;
}
```

- 동일한 내용을 `config/tailwind.config.js` 파일에도 `extends` 부분에 아래와 같이 추가해두었으나 적용되지 않습니다. tailwindconfig로 애니메이션을 커스텀하는 것에 계속 실패한다면 해당 코드는 삭제하도록 하겠습니다.
```js
keyframes: {
        slider: {
          '0%': {
            transform: 'translateY(0px)'
          },
          '100%': {
            transform: 'translateY(100px)'
          }
        }
 },
 animation: {
        slider: 'slider 5s linear infinite'
 }
```

## 👻 질문 사항

> 메인 배너 이미지

- 영상으로 대체할 것인지, 해당 이미지를 그대로 사용할 것인지, Three.js를 사용할 것인지 협의가 필요할 것 같습니다. (우선은 figma에서 그대로 exports하여 구현해두었습니다.) 해당 이미지를 그대로 사용하게 될 경우 이미지를 layer별로 추출하여 반응형이 적용되도록 수정할 예정입니다.

> 스크롤 이벤트

- 캡쳐 영상에서처럼 하단에 다른 컴포넌트가 존재하지 않을 경우 의도대로 스크롤 이벤트가 자연스럽게 동작하지만 아래에 다른 컴포넌트들이 추가되어 스크롤이 아래로 길어질 경우 화면 단위의 스크롤 이벤트가 적용되지 않습니다.
- 스크롤 단위 이벤트를 적용하기 위해서는 scroll에 대한 eventListener의 passive 속성을 조정해야 하는데 이럴 경우 전체 랜딩 페이지의 스크롤이 영향을 받게 됩니다.
- AOS 등의 스크롤 이벤트 라이브러리 도입을 고려해볼 필요도 있을 것 같습니다.

> 이미지 슬라이드

- 스크롤 이벤트를 통해 보여지는 화면이 변하면 슬라이드 애니메이션이 초기화되는 문제가 있습니다.

2024-06-18 10:53 UTC, Zero-1016 requested changes
고생하셨습니다~!

글자 슬라이드가 왼쪽 위에 있어서 뭔가 어색한 것 같네요 오른쪽 슬라이드 배너도 이미지가 더 추가가 되면 예뻐질 것 같습니다.

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/app/page.tsx
> +    <main className='flex min-h-screen flex-col items-center justify-between'>
렌딩 페이지 자체가 `<main/>` 태그로 감싸져있습니다. 
```html
<main>
   <main><LandingPageContent /></main>
</main
```

`page.tsx` 에서는 `meta` 태그나 `searchParams`, `params`를 넘겨주는 정도만 일을 하면 될 것 같습니다. 바로 `import`를 해서 넣어주는 것도 좋아보입니다.

```tsx
export const metadata: Metadata = {
  title: 'Example Title',
  description: 'Example description',
}

type Props = {
  params: {
    postId: string
  }
}

export default function Page({ params: { postId} }: Props) {
  return (
      <PostDetail postId={postId} />
  )
}
```

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/app/layout.tsx
> +      <body className={inter.className}>
각 페이지 마다 기본이 되는 폰트를 주고있어요 `pretendard.className` 해당 `className`은 그냥 지워도 될 것 같네요

2024-06-18 10:53 UTC, Zero-1016 commented on packages/ui/src/button.tsx
> +export type ButtonProps = {
굳이 `type`을 `export`하지 않아도 `ComponentPropsWithoutRef<typeof Button>` 타입으로 접근할 수 있습니다!

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/link/ui/NavigationButton.tsx
> +import { ButtonProps } from 'node_modules/@repo/ui/src/button'
`type`을 따로 가져올 필요는 없을것 같아요! `node_modules`에 직접적으로 접근을 하는게 좋은건지 의문이 드네요!

만약에 타입을 불러온다고 해도 `@repo/ui/src/button` 해당 방식을 이용할 것 같아요.

>node_modules에 직접 접근하는 것의 문제점은 다음과 같습니다:
>
>1. 경로 변경 가능성: node_modules 내부의 구조나 파일 경로는 패키지 업데이트 시 변경될 수 있습니다. 이는 코드의 안정성을 해칠 수 있습니다.
>
>2. 가독성 저하: 직접 node_modules 경로를 참조하면 코드 가독성이 떨어집니다. 다른 사람들이 이해하기 어려울 수 있습니다.
>
>3. 타입 안전성: TypeScript에서는 node_modules에 접근하는 것보다 타입을 정의한 모듈 경로를 명시적으로 import하는 것이 더 안전합니다.

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/nav/constants/navTabs.ts
> +] as const
저희 불필요한 `as const`는 사용하지 말자고 얘기를 했던 것 같습니다!

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/nav/lib/use-nav-tab.ts
커스텀 함수로 분리하신 부분이 좋은 것 같아요!

가독성이 좋아보이네요

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +        <Nav.NavLogo
`Nav`가 반복이 되고 있어요 하나의 객체로 묶어줬다면 포함되고 있는 것을 알고있느니 중복된 이름은 제거해도 될 것 같습니다.

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +              onClick={() => handleTabClick(tab.text, tab.href)}>
다음처럼 코드를 클로저를 사용한 고차함수로 예쁘게 변경할 수 있을꺼 같아요

```tsx
const onMove = (tab: NavTab) => () => {
  handleTabClick(tab.text, tab.href)
}
```

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +import { NAV_TABS } from '../constants'
절대경로를 사용하면 통일성이 있을 것 같습니다.

2024-06-18 10:53 UTC, Zero-1016 commented on apps/academy/src/widget/landing/ui/index.ts
다른 추상화 단계에서 사용하는 `MainBanner` 컴포넌트의 경우도 분리해도 될 것 같습니다!

2024-06-19 11:38 UTC, JeongwooHam commented
> 고생하셨습니다~!
> 
> 글자 슬라이드가 왼쪽 위에 있어서 뭔가 어색한 것 같네요 오른쪽 슬라이드 배너도 이미지가 더 추가가 되면 예뻐질 것 같습니다.

글자 슬라이드는 피그마 상에 텍스트가 좌측 상단에 위치에 있어서 그렇게 구현하였는데 다들 동의하시면 중앙에 위치하게 바꿔도 예쁠 것 같네요!
이미지 슬라이드는 PR에 작성한 것처럼 페이지 내릴 때마다 슬라이드 초기화 되는 것만 해결하면 원래 추가해둔 다른 이미지들도 잘 보일 것 같습니다.

2024-06-19 13:09 UTC, JeongwooHam commented on apps/academy/app/page.tsx
> +    <main className='flex min-h-screen flex-col items-center justify-between'>
`main` 태그가 중복되었네요! 최상단 `page.tsx`에서는 랜딩 페이지를 `import`만 하도록 수정하여 push 하였습니다. 말씀해주신 `meta` 태그 같은 것들은 zoey님께서 이미 구현하신 코드가 있어 충돌이 생길 것 같아 별도로 수정하진 않았습니다!

2024-06-19 13:10 UTC, JeongwooHam commented on apps/academy/app/layout.tsx
> +      <body className={inter.className}>
`className`과 `inter`에 대한 `import` 코드를 삭제하였습니다.

2024-06-19 13:10 UTC, JeongwooHam commented on packages/ui/src/button.tsx
> +export type ButtonProps = {
훨씬 가독성 좋은 방법이네요! 다른 컴포넌트 구현 시에도 적극 활용하겠습니다. 해당 타입으로 수정하였습니다!

2024-06-19 13:12 UTC, JeongwooHam commented on apps/academy/src/feature/link/ui/NavigationButton.tsx
> +import { ButtonProps } from 'node_modules/@repo/ui/src/button'
자동 `import` 완성을 사용하여 `node_modules`에서 바로 `import` 된 것을 확인하지 못했네요! 말씀해주신 `ComponentPropsWithoutRef`를 사용하도록 수정한 뒤 해당 코드는 삭제하였습니다.

2024-06-19 13:13 UTC, JeongwooHam commented on apps/academy/src/feature/nav/constants/navTabs.ts
> +] as const
삭제 후 커밋하였습니다!

2024-06-19 13:13 UTC, JeongwooHam commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +        <Nav.NavLogo
다시 보니 동일한 이름이 불필요하게 반복되고 있네요! `Nav.Logo`처럼 `Nav`가 한 번만 사용되도록 수정하였습니다.

2024-06-19 13:14 UTC, JeongwooHam commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +              onClick={() => handleTabClick(tab.text, tab.href)}>
오 생각지도 못한 방식인데 깔끔하고 좋네요! 말씀해주신 대로 수정해보았습니다:)

2024-06-19 13:14 UTC, JeongwooHam commented on apps/academy/src/feature/nav/ui/NavBar.tsx
> +import { NAV_TABS } from '../constants'
같은 폴더 내에서는 상대 경로로 `import` 되었었네요..! 다른 파일에서도 상대 경로가 사용되지 않도록 수정 완료하였습니다!

2024-06-19 13:18 UTC, JeongwooHam commented on apps/academy/src/widget/landing/ui/index.ts
이거는 어떤 식으로 분리하는 것을 생각하신 것인지 궁금합니다..! 현재 `widget` 폴더 대신 다른 폴더로 옮기시는 것을 말씀하시는 걸까요? (개인적으로는 구현해주신 지원하기 페이지의  `ApplyScheduleBanner`과 비슷한 컴포넌트라고 생각했습니다..!)

2024-06-19 13:51 UTC, zivivle commented on apps/academy/src/feature/nav/lib/use-nav-tab.ts
> +    cn(
cn이 꼭 필요한걸까요?
```js
const handleTabClassName = (isTargetTab: boolean) =>
    `cursor-pointer hover:text-primary hover:font-bold text-text-body-1 px-6 py-8 ${
      isTargetTab ? 'text-base font-bold text-primary leading-[120%]' : ''
    }`
```
이렇게 하면 어떨까요!

2024-06-19 13:55 UTC, zivivle commented on apps/academy/src/widget/landing/constants/MobiDescription.ts
> +export const MOBI_DESCRIPTION = [
widget에 constants를 만들어서 사용해도 좋겠네요! 저도 이렇게 수정해서 적용해보겠습니다 :) 👍

2024-06-19 15:20 UTC, Zero-1016 commented on apps/academy/src/widget/landing/ui/index.ts
`View`와 같이 다른 단계의 추상화 단계로 갈 경우 해당 `index.ts` 파일에 추가해도 될 것 같다는 얘기였습니다!

2024-06-20 08:33 UTC, yesoryeseul commented
고생하셨습니다. 이미지 슬라이드 문제는 저도 코드 한번 확인해보겠습니다.

메인 -> 다음 섹션으로 이동할 때 이미지 슬라이드 상단이 잘려나오는 게 너무 잘 보이는 거 같아 메인 -> 다음 섹션으로 이동할 때도 스크롤로 내려가는 것보다 아래 섹션 구현하신 것처럼 화면이 전환되는 느낌을 주어도 좋을 것 같습니다.

애니메이션이 조금 어색한 느낌이 드는데 초기화 문제 때문에 그런 것 같기도 합니다. 이건 하면서 조금씩 더 손보면 될 것 같네요.

2024-06-20 08:34 UTC, yesoryeseul approved these changes

2024-06-21 20:16 UTC, JeongwooHam commented on apps/academy/src/widget/landing/ui/index.ts
아하 이해했습니다. 해당 커밋에서 수정해두었습니다!

[Commit 링크](https://github.com/team-mobi/mobi-client/pull/6/commits/dc7af20a039094565b1176986b11298b29d0dc69)

2024-06-21 20:31 UTC, JeongwooHam commented
> 고생하셨습니다. 이미지 슬라이드 문제는 저도 코드 한번 확인해보겠습니다.
> 
> 메인 -> 다음 섹션으로 이동할 때 이미지 슬라이드 상단이 잘려나오는 게 너무 잘 보이는 거 같아 메인 -> 다음 섹션으로 이동할 때도 스크롤로 내려가는 것보다 아래 섹션 구현하신 것처럼 화면이 전환되는 느낌을 주어도 좋을 것 같습니다.
> 
> 애니메이션이 조금 어색한 느낌이 드는데 초기화 문제 때문에 그런 것 같기도 합니다. 이건 하면서 조금씩 더 손보면 될 것 같네요.

이미지 슬라이드보다 이미지 전환이 더 예뻐보일수도 있겠네요..! 둘 다 구현해보고 의견을 여쭤보겠습니다.

2024-06-21 20:41 UTC, JeongwooHam commented on apps/academy/src/feature/nav/lib/use-nav-tab.ts
> +    cn(
삼항연산자를 잘 사용하지 않는 편이라 `&&`으로 구현하였는데 말씀해주신대로 cn이 없어도 문제가 없겠네요! 수정하여 반영해두었습니다.

[Commit 링크](https://github.com/team-mobi/mobi-client/pull/6/commits/cbce52a7d224a9a6e43e581385c1259df3b83a3c)

2024-06-22 02:40 UTC, zivivle approved these changes

2024-06-22 03:39 UTC, Zero-1016 approved these changes

2024-06-22 05:41 UTC, merged