[MOBI-28-curriculum-schedule-desktop-publishing] 커리큘럼 및 일정 데스크탑 퍼블리싱을 완료합니다.
team-mobi/mobi-client pull request #9
Opened 2024-06-21 17:21 UTC by yesoryeseul

## 🌱 작업 개요

- 메인 하단 섹션의 커리큘럼 및 일정 데스크탑 퍼블리싱을 진행하였습니다.

## 🧐 중요한 변경 사항

![CPT2406220208-1654x779](https://github.com/team-mobi/mobi-client/assets/123865139/70a512c8-709c-4856-9875-fdb49f4fa37c)

#### tsconfig.json.js
- [ ] 롤링 기능의 keyframe과 animation 추가가 있습니다.
- [ ] backgroundImage에 curriculum에 사용되는 gradient 코드 추가 있습니다. 접두어를 모두 curriculum- 로 하여 구분할 수 있도록 했습니다. 만약 겹치는 속성이 있다면 공용적인 이름으로 수정해도 될 것 같습니다.
- [ ] color에 glass-stroke 속성을 추가하였습니다.

#### global.css
- [ ] animate-rollingleft1, animate-rollingleft2 코드 추가 있습니다. 지금 생각해보니 rollingleft1, rollingleft2 명칭이 조금 그렇네요 해당 섹션명과 맞추어 변경하겠습니다.

## 👻 질문 사항

- 커리큘럼 카드가 첫 번째, 두 번쨰 영역은 데이터가 3개이고 각 border-radius가 다릅니다. (첫 번째는 왼쪽 위만, 두 번째는 없음, 세 번째는 오른쪽 위만)

그런데 모바일로 왔을 때는 데이터가 하나인 것처럼 양쪽 위 모두 border가 먹어야 합니다. 지금 당장은 index를 감지해서(함수) radius를 설정 해두었는데 모바일에서는 해당 부분을 변경하여야 할 것 같습니다. 지금 당장 생각 나는 방법은 없어서 일단 데스크탑 부분을 먼저 올리도록 하겠습니다. 의견이 있다면 알려주세요..

- 롤링 부분이 조금 어색한 부분이 있습니다. 다른 방식의 구현 방법이 있을까요?(StackBanner.tsx 참고)

2024-06-22 07:11 UTC, Zero-1016 requested changes
고생하셨습니다.

이전 커밋과 비교하였을 때 반응형 처리, 애니메이션 적용과 같이 변동된 부분들이 많습니다.

해당 부분 잘 확인하셔서 변경해주시면 될 것 같습니다.!

2024-06-22 07:11 UTC, Zero-1016 commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +  boundaryProps: { isFirst: boolean; isLast: boolean; isSingle: boolean }
중복된 타입이 발생하는 것 같습니다. `{ isFirst: boolean; isLast: boolean; isSingle: boolean }`를 분리하면 좋을 것 같네요

```ts
type SubjectProps = {
  className?: string
  isFirst?: boolean
  isLast?: boolean
  isSingle?: boolean
} & VariantProps<typeof subjectStyles>
```

2024-06-22 07:11 UTC, Zero-1016 commented on packages/config/tailwind.config.js
> +      keyframes: {
해당 [링크](https://github.com/team-mobi/mobi-client/pull/8#issuecomment-2183861936) 참고하셔서 애니메이션을 수정해주시면 좋을 것 같습니다.

`globals.css`는 반복되는 클래스 이름을 간소화 시키는 정도로 생각하면 좋을 것 같아요. 그 외에는 tailwind-config에서 작업하는 것이 좋아보입니다.

2024-06-22 07:11 UTC, Zero-1016 commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +      <div className='absolute bottom-[60px] left-8 right-8 z-[1] m-auto h-px max-w-[1180px] bg-green'></div>
아래로 수정해도 될 것 같습니다.

```suggestion
      <div className='absolute bottom-[60px] left-8 right-8 z-[1] m-auto h-px max-w-[1180px] bg-green' />
```

2024-06-22 08:05 UTC, JeongwooHam approved these changes
고생하셨습니다!:)

## 👻 질문에 대한 답변

> 첫 번째 `border-radius` 관련 질문의 경우 내용이 잘 이해가 되지 않네요 죄송합니다🥹 다음에 시간 괜찮으실 때 실제 화면으로 보여주신다면 더 좋은 방안이 있을지 찾아보겠습니다!

> 롤링 부분은 봤을 때 어색함이 느껴지지는 않는데 비슷한 느낌으로 구현된 예시들이 있어 첨부해둡니다!

- [Tailwind Infinite Slider_1](https://codepen.io/canIHaveSome/pen/vYzPzWM)
- [Tailwind Infinite Slider_2](https://codepen.io/abhikb/pen/yLgMvGw)
- [Infinite Autoplay Carousel](https://codepen.io/studiojvla/pen/qVbQqW)
- [Creating an infinite logo carousel with pure CSS](https://youtu.be/nAjR0Oj0J8E?si=p5qiVp4qf20xEC7I)
  
> 이미지 파일의 경우 `academy`에 페이지가 엄청 많지 않아 화질이 깨진다면 webp 파일을 사용하지 않아도 용량에 큰 문제 없을 것 같습니다!

2024-06-22 08:05 UTC, JeongwooHam commented on apps/academy/src/feature/rolling/ui/StackBanner.tsx
> +
`imageList` 영역을 `useCallback`으로 감싸거나 아래 예시처럼 컴포넌트를 분리하여 사용하는 것도 좋을 것 같습니다!

### 예시

```ts
export function StackBanner( ){
  const { cloneCreated } = useCloneRollingBanner()
  
  return (
    <div className='relative flex overflow-hidden'>
      <ImageList className='curriculum-stack-original'/>
      <ImageList className='clone' isRendered={ cloneCreated }/>
    </div>
  )
}

type Props = {
  className: string
  isRendered?: boolean
}

function ImageList({ className, isRendered = true }: Props){
  if(!isRendered) return <></>

  return (
  // ...
  )
}
```

2024-06-22 09:34 UTC, zivivle approved these changes
코드와 리뷰들 모두 확인했습니다! 제가 추가로 리뷰할 부분은 없는 것 같네요.

[질문에 대한 답변]
- border-radius 부분은 제로님이 지정해주신 미디어쿼리 hidden을 사용해서 데스크탑 부분만 숨기고, 모바일일 경우에는 index가 아닌 양쪽 border-radius가 적용된 컴포넌트를 보여주면 어떨까요?
- 저도 롤링 부분이 어색하다고 느껴지진 않았는데, 혹시 보기에 걸리시는 부분이 있으신걸까요?
- webp로 변환하는 것이 화질에 영향이 없는 무손실 압축 방법이라고 들었습니다. 
제로님이 말씀하신 대로 webp나 avif를 사용하는 것이 좋다고 생각합니다. :) 
혹시 화질이 어떻게 차이가 나는지 알 수 있을까요?

2024-06-22 10:54 UTC, Zero-1016 commented
질문에 대한 답변입니다

- 커리큘럼 카드 한 층을 하나의 컴포넌트로 보고 boder-radius를 적용하는 방법은 어떠신가요? grid를 사용하면 될 것 같습니다.
- 롤링 부분 어색한 부분을 확인을 하려고 보아하니 볼 수 있는 컴포넌트나 스토리북이 없어서 직접 확인을 하진 못하였습니다. 어느 부분에서 어색한 부분이 있으신지 궁금합니다.
- 용량 문제는 별로 차이가 안나서 괜찮습니다.

2024-06-23 09:09 UTC, yesoryeseul commented on packages/config/tailwind.config.js
> +      keyframes: {
해당 부분 반영하였습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: tailwindcss 적용, xl: 제거 및 mobile: 추가](https://github.com/team-mobi/mobi-client/pull/9/commits/b6e28fcb18668b1f974dd6dec611d0fcbf03997c)

2024-06-23 09:10 UTC, yesoryeseul commented on apps/academy/src/common/styles/globals.css
> +  @apply animate-stackBannerLoop;
아 이거 아래 clone 이라는 것도 사용을 합니다! 두개가 keyframe 방식이 달라요. 현재는 명칭을 바꾸어 tailwindcss-animate 적용하였습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: tailwindcss-animate 적용, xl: 제거 및 mobile: 추가](https://github.com/team-mobi/mobi-client/pull/9/commits/b6e28fcb18668b1f974dd6dec611d0fcbf03997c)

2024-06-23 09:12 UTC, yesoryeseul commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +  return <ul className={cn('flex gap-px xl:w-full xl:max-w-[1244px]', className)}>{children}</ul>
xl: md: 를 사용하는 부분은 일단 제거 하였습니다. 모바일 작업하면서 좀 더 세분화해보겠습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: tailwindcss-animate 적용, xl: 제거 및 mobile: 추가](https://github.com/team-mobi/mobi-client/pull/9/commits/b6e28fcb18668b1f974dd6dec611d0fcbf03997c)

2024-06-23 09:33 UTC, yesoryeseul commented on apps/academy/src/widget/landing/constants/stackImages.ts
> +    id: 'Html',
해당 부분 반영하였습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: px -> rem, image id -> number, tag close, PropsNeedChildren 변경](https://github.com/team-mobi/mobi-client/pull/9/commits/15a7981e4b6c4f2f08f707556fdc63af87ec507d)

2024-06-23 09:33 UTC, yesoryeseul commented on apps/academy/src/feature/rolling/ui/StackBanner.tsx
> +          className='h-[96px] w-[96px] flex-none'>
앗 24가 있는지 확인하지 못했네요! 수정 반영하였습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: px -> rem, image id -> number, tag close, PropsNeedChildren 변경](https://github.com/team-mobi/mobi-client/pull/9/commits/15a7981e4b6c4f2f08f707556fdc63af87ec507d)

2024-06-23 09:34 UTC, yesoryeseul commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +      <div className='absolute bottom-[60px] left-8 right-8 z-[1] m-auto h-px max-w-[1180px] bg-green'></div>
반영하였습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: px -> rem, image id -> number, tag close, PropsNeedChildren 변경](https://github.com/team-mobi/mobi-client/pull/9/commits/15a7981e4b6c4f2f08f707556fdc63af87ec507d)

2024-06-23 09:34 UTC, yesoryeseul commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +}
오..전부 저렇게 해놓은 부분 다 수정하여 반영했습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: px -> rem, image id -> number, tag close, PropsNeedChildren 변경](https://github.com/team-mobi/mobi-client/pull/9/commits/15a7981e4b6c4f2f08f707556fdc63af87ec507d)

2024-06-23 09:38 UTC, yesoryeseul commented
> 고생하셨습니다.
> 
> 이전 커밋과 비교하였을 때 반응형 처리, 애니메이션 적용과 같이 변동된 부분들이 많습니다.
> 
> 해당 부분 잘 확인하셔서 변경해주시면 될 것 같습니다.!

### 1. 반응형 처리
- xl: md: 있는 부분은 일단 전부 제거하고 모바일 작업에서 세분화하도록 하겠습니다!

### 2. 애니메이션 적용
- 해당 부분 전부 반영하였고 animation 부분 global.css 에서도 제거하였습니다.

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: tailwindcss-animate 적용, xl: 제거 및 mobile: 추가](https://github.com/team-mobi/mobi-client/pull/9/commits/b6e28fcb18668b1f974dd6dec611d0fcbf03997c)

2024-06-23 09:39 UTC, yesoryeseul commented
> 고생하셨습니다!:)
> 
> ## 👻 질문에 대한 답변
> > 첫 번째 `border-radius` 관련 질문의 경우 내용이 잘 이해가 되지 않네요 죄송합니다🥹 다음에 시간 괜찮으실 때 실제 화면으로 보여주신다면 더 좋은 방안이 있을지 찾아보겠습니다!
> 
> > 롤링 부분은 봤을 때 어색함이 느껴지지는 않는데 비슷한 느낌으로 구현된 예시들이 있어 첨부해둡니다!
> 
> * [Tailwind Infinite Slider_1](https://codepen.io/canIHaveSome/pen/vYzPzWM)
> * [Tailwind Infinite Slider_2](https://codepen.io/abhikb/pen/yLgMvGw)
> * [Infinite Autoplay Carousel](https://codepen.io/studiojvla/pen/qVbQqW)
> * [Creating an infinite logo carousel with pure CSS](https://youtu.be/nAjR0Oj0J8E?si=p5qiVp4qf20xEC7I)
> 
> > 이미지 파일의 경우 `academy`에 페이지가 엄청 많지 않아 화질이 깨진다면 webp 파일을 사용하지 않아도 용량에 큰 문제 없을 것 같습니다!

1. 먼저 해결해보겠습니다
2. 오오 감사합니다. 리팩토링 하면서 적용해보겠습니다!

2024-06-23 11:10 UTC, Zero-1016 approved these changes

2024-06-23 12:26 UTC, yesoryeseul commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +  boundaryProps: { isFirst: boolean; isLast: boolean; isSingle: boolean }
이 부분 아마 수정하면 안 쓰게 될 타입일 수도 있긴한데 분리된 후 여기서 수정이 될 수도 있어서 변경해두었습니다

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: 겹치는 타입 분리, StackImage 조건부 분리](https://github.com/team-mobi/mobi-client/pull/9/commits/e6173ab3dde5769f47f2f3c6a33fa987967c4cc0)

2024-06-23 12:27 UTC, yesoryeseul commented on apps/academy/src/feature/rolling/ui/StackBanner.tsx
> +
오 둘 다 좋은 의견 같습니다. 저는 코드 작성해주신 것처럼 컴포넌트를 분리해서 푸시해봤는데 의도하신 게 맞게 반영 되었을까요?

[[MOBI-28-curriculum-schedule-desktop-publishing] Refactor: 겹치는 타입 분리, StackImage 조건부 분리](https://github.com/team-mobi/mobi-client/pull/9/commits/e6173ab3dde5769f47f2f3c6a33fa987967c4cc0)

2024-06-23 12:28 UTC, Zero-1016 commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +  boundaryProps: { isFirst: boolean; isLast: boolean; isSingle: boolean }
수정하면 필요없을 것 같아요!

2024-06-23 12:30 UTC, yesoryeseul commented
> 코드와 리뷰들 모두 확인했습니다! 제가 추가로 리뷰할 부분은 없는 것 같네요.
> 
> [질문에 대한 답변]
> 
> * border-radius 부분은 제로님이 지정해주신 미디어쿼리 hidden을 사용해서 데스크탑 부분만 숨기고, 모바일일 경우에는 index가 아닌 양쪽 border-radius가 적용된 컴포넌트를 보여주면 어떨까요?
> * 저도 롤링 부분이 어색하다고 느껴지진 않았는데, 혹시 보기에 걸리시는 부분이 있으신걸까요?
> * webp로 변환하는 것이 화질에 영향이 없는 무손실 압축 방법이라고 들었습니다.
>   제로님이 말씀하신 대로 webp나 avif를 사용하는 것이 좋다고 생각합니다. :)
>   혹시 화질이 어떻게 차이가 나는지 알 수 있을까요?
<img width="108" alt="스크린샷 2024-06-23 오후 9 28 45" src="https://github.com/team-mobi/mobi-client/assets/123865139/d6477caf-3354-463b-970e-8f875f53905d">

이런 느낌으로 차이가 나는데 모든 이미지가 저렇게 하면 깨지고 예뻐보이지 않더라구요! svg가 문제 없는 거 같아서 svg로 사용하겠습니다

2024-06-23 12:34 UTC, yesoryeseul commented
> 질문에 대한 답변입니다
> 
> * 커리큘럼 카드 한 층을 하나의 컴포넌트로 보고 boder-radius를 적용하는 방법은 어떠신가요? grid를 사용하면 될 것 같습니다.
> * 롤링 부분 어색한 부분을 확인을 하려고 보아하니 볼 수 있는 컴포넌트나 스토리북이 없어서 직접 확인을 하진 못하였습니다. 어느 부분에서 어색한 부분이 있으신지 궁금합니다.
> * 용량 문제는 별로 차이가 안나서 괜찮습니다.

의견 감사합니다. grid 사용하는 방법을 이번 pr이 아닌 모바일을 진행하면서 해보겠습니다!

2024-06-23 12:34 UTC, yesoryeseul commented on apps/academy/src/widget/landing/ui/CurriculumScheduleCard.tsx
> +  boundaryProps: { isFirst: boolean; isLast: boolean; isSingle: boolean }
모바일 작업하면서 필요 없으면 지우겠습니다

2024-06-23 12:36 UTC, merged